version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.2-node-browsers
    working_directory: ~/my-article-app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            bundle install
            yarn install
      - run:
          name: 
          command: |
            bundle exec rspec
            # Add commands to run your frontend tests here if applicable
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: circleci/ruby:3.0.2-node-browsers
    working_directory: ~/my-article-app
    steps:
      - attach_workspace:
          at: ~/my-article-app
      - run:
          name: Deploy to production
          command: |
            # Add commands to deploy your application to production here

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
